version: "3"

volumes:
  mongodb_volume:

services:
  work:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8080:8080
  mongo:
    image: "mongo:latest"
    volumes:
      - mongodb_volume:/data/db
    restart: always